### ISSUE TITLE
TreeNode

### ISSUE THREAD

**Issue by neu1886** [fire-eggs/Ancestral-Tree#17]
Could you please show us the structure of a TreeNode? I mean, couldn't find the main TreeNode Declaration.

**Comment by fire-eggs** [comment]
It has gotten a little messy and I've not refactored yet.

The tree data classes and factory are in TreeModel/TreeData.cs.

The "driver" data for the `AbstractTreeLayout` is defined by `ITreeData`:
```
        int Wide { get; }
        int High { get; }
        int ParentConnectLoc { get; }
        bool Vertical { get; }
```
Of those fields, only `High` and `Wide` matter for layout. Most of the data node fields are for drawing, and thus a failure on my part of abstraction ...

The two concrete `ITreeData` classes are `PersonNode` and `UnionNode`. A `UnionNode` contains the two `PersonNode`s for a GEDCOM FAM record - thus a different `Wide` calculation than a `PersonNode`. The `PersonNode` represents the box for a single unmarried person, or the spouses in multiple marriages. 

The `NodeFactory` does the work of creating the nodes - the text to be displayed (and the resulting width and height), and other pre-calculated data.

The [Abego Tree Layout](http://treelayout.sourceforge.net/)  page might have some useful information / background. 

If you have a specific question or area of interest, let me know!
Kevin

**Comment by neu1886** [comment]
Hi Kevin,

thanks for your reply. Is there an e-Mail address, so I can go into detail with you? Would be nice.

Thanks

**Comment by fire-eggs** [comment]
Sure, here I am!

**Comment by neu1886** [comment]
Sorry Kevin, I didn't see any e-Mail Address, only the official GitHub mail. So I got your message from notifications@github.com. Don't wanna communicate public.

**Comment by fire-eggs** [comment]
Arrgh! Github confuses me sometimes.

lifeattickville@gmail.com is the best email address.
